version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /usr/sbin/apache2ctl -D FOREGROUND
    volumes:
      - .:/var/www/html:rw
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - cloud-sql-proxy

  cloud-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.22.0
    command: /cloud_sql_proxy -instances=resourceloadfailure:asia-northeast1:for-third=tcp:0.0.0.0:3306 -credential_file=/secrets/cloudsql/key.json
    volumes:
      - ./secrets:/secrets
    ports:
      - "3306:3306"
